name: test1
on: 
	issues:
		types: [opened]
	label:
		types: [created]
jobs:	
	action:
		runs-on: ubuntu-latest
		steps: 
			-name: print trigger
			 run: echo "Trigger - ${{ github.event.label.name }}"
			-run: echo "user - ${{ github.actor }}"ž
			-run: date
			
